name: Sync Fork

on:
  schedule:
    - cron: '20 4 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: wayfair-incubator/forker@v0.0.6
      #tgymnich/fork-sync@v2.0.10
        with:
          owner: qist
          base: master
          head: master
